'use client';

import type { Section } from '../types';
import { TOS_COGNITIVE_LEVELS } from '../utils/tosPlan';
import { buildTosReviewModel, type TosReviewWarning } from '../utils/tosReviewState';

export interface TosReviewProps {
  section: Section | undefined;
}

function warningKey(warning: TosReviewWarning, index: number): string {
  return `${warning.code}-${warning.path}-${index}`;
}

export default function TosReview({ section }: TosReviewProps) {
  const model = buildTosReviewModel(section);
  if (!model.visible) return null;

  return (
    <section className="tos-review" aria-label="Table of Specifications review">
      <div className="tos-review__heading">
        <div>
          <h3>Saved TOS review</h3>
          <p>Read-only summary for this worksheet section.</p>
        </div>
        <span className="tos-review__badge">Informational</span>
      </div>

      {model.warnings.length > 0 && (
        <div className="tos-review__warnings" role="alert">
          <strong>Review warnings</strong>
          <ul>
            {model.warnings.map((warning, index) => (
              <li key={warningKey(warning, index)}>{warning.message}</li>
            ))}
          </ul>
        </div>
      )}

      {model.planValid ? (
        <>
          <div className="tos-review__metrics" role="status">
            <span>
              Allocated total
              <strong>{model.allocatedTotal}</strong>
            </span>
            <span>
              Generated TOS questions
              <strong>{model.generatedTotal}</strong>
            </span>
          </div>

          <div className="tos-review__rows">
            {model.rows.map((row) => (
              <article className="tos-review__row" key={row.id}>
                <h4>{row.competency}</h4>
                {row.objective !== undefined && row.objective.length > 0 && (
                  <p className="tos-review__objective">Objective: {row.objective}</p>
                )}

                <div className="tos-review__levels" aria-label={`${row.competency} allocations`}>
                  {TOS_COGNITIVE_LEVELS.map((level) => (
                    <span className="tos-review__level" key={`allocation-${level}`}>
                      {level}
                      <strong>{row.allocations[level] ?? 0}</strong>
                    </span>
                  ))}
                </div>
                <p className="tos-review__label">Generated by cognitive level</p>
                <div className="tos-review__levels" aria-label={`${row.competency} generated counts`}>
                  {TOS_COGNITIVE_LEVELS.map((level) => (
                    <span className="tos-review__level" key={`generated-${level}`}>
                      {level}
                      <strong>{row.generatedCounts[level] ?? 0}</strong>
                    </span>
                  ))}
                </div>
                <div className="tos-review__totals">
                  <span>Allocated: {row.allocatedTotal}</span>
                  <span>Generated: {row.generatedTotal}</span>
                </div>
              </article>
            ))}
          </div>
        </>
      ) : (
        <p className="tos-review__unavailable">
          The saved TOS details cannot be safely summarized. Review the warning above; no data was corrected automatically.
        </p>
      )}
    </section>
  );
}
